### ISSUE TITLE
Files in / are linked beginning with "//"

### ISSUE THREAD

**Issue by sfanxiang** [HaikuArchives/GenesisCommander#2]
If you choose a file in /, and select "Commands->Create link on Desktop", the link created will begin with "//". This isn't causing any problems, but would be more natural to begin with "/" like other links.

**Comment by ocerman** [comment]
@humdingerb This can be closed

**Comment by humdingerb** [comment]
Thanks for the note. Turns out the keyword to auto-close issues is, e.g. "Fixes #2". "Fixes issue #2" doesn't seem to work...
