### ISSUE TITLE
Use Tracker Icons for system folders and devices

### ISSUE THREAD

**Issue by diversys** [HaikuArchives/GenesisCommander#24]
https://git.haiku-os.org/haiku/tree/src/kits/tracker/TrackerIcons.rdef

**Comment by ocerman** [comment]
hello @diversys,
the function `node.GetTrackerIcon` is already used for getting the icons. I was expecting that it would return same icon as tracker, but that's not always the case.

If it is possible, maybe it would be better to change function `node.GetTrackerIcon` in the upstream so it would return always actual tracker icon.

**Comment by diversys** [comment]
I'm not a real coder so I can't comment on that :) But you can upload a patch to Gerrit https://review.haiku-os.org/

**Comment by pulkomandy** [comment]
On Sat, Dec 21, 2019 at 10:38:44PM +0000, Ondrej Čerman wrote:
> hello @diversys,
> the function `node.GetTrackerIcon` is already used for getting the icons. I was expecting that it would return same icon as tracker, but that's not always the case.
> 
> If it is possible, maybe it would be better to change function `node.GetTrackerIcon` in the upstream so it would return always actual tracker icon.

Known bug, LnLauncher has the same problem. I tink I already opened a
ticket about it for Haiku?

**Comment by ocerman** [comment]
I found this ticket: https://dev.haiku-os.org/ticket/9480

I think this issue can be closed here.

**Comment by humdingerb** [comment]
Thanks for tracking it down.
