### ISSUE TITLE
Remove unfinished multilanguage implementation

### ISSUE THREAD

**Issue by ocerman** [HaikuArchives/GenesisCommander#41]
GenesisCommander do not use Haiku's locale kit but own multilanguage implementation.
The issue is that:
- it is barely used - basically just menu items and few other string are translated, everything else is hardcoded English-only
- compared to haiku's system, the multilanguage capabilities are quite limited
- it is unfinished - there is no way for end user to actually switch to another language in GUI
- there is only 1 translation that is unfinished and unmaintained.

I think the best option would be to remove this this multilanguage implementation. In the future the haiku's locale kit can be used.

**Comment by humdingerb** [comment]
I agree.
The first and most difficult step to localization is re-writing everything using layout management.

**Comment by KapiX** [comment]
Maybe this will be useful: http://kacperkasper.pl/commander/

I created it a loooong time ago, and it is basically a mockup, but it could at least save you a hassle of recreating main window with layouts :)
