### ISSUE TITLE
Overwrite do not remove leftover data

### ISSUE THREAD

**Issue by ocerman** [HaikuArchives/GenesisCommander#42]
When a file is copy-overwritten with smaller file, the leftover data is not deleted.
For example:
Original file:
```
aaa
aaa
aaa
```
Copy and overwrite with file:
```
bbb
bbb
```
The result is:
```
bbb
bbb
aaa
```
Instead of expected:
```
bbb
bbb
```

**Comment by humdingerb** [comment]
Great bug... :}
