### ISSUE TITLE
Too many alerts to abort deletion of a non-empty folder

### ISSUE THREAD

**Issue by humdingerb** [HaikuArchives/GenesisCommander#52]
When deleting a non-empty folder you get this Alert1 (including typo "realy":

![Alert1](https://linx.li/s/screenshot1112.png)

When the folder isn't empty, you get these 2 alerts:

![Alert2+3](https://linx.li/s/screenshot1113.png)

If you delete a single folder, the "Delete all" button isn't needed.

If you click "Abort", the "Delete in progress..." alert remains, until you click "Abort" on that one, too. And on top of that, you get a 4th alert:

![Alert4](https://linx.li/s/screenshot1114.png)

Alert4 is unnecessary, but if needed elsewhere, should have the buttons "Cancel" and "Abort" instead of Yes/No.

**Comment by humdingerb** [comment]
Same issues when deleting a non-empty folder

**Comment by humdingerb** [comment]
> Same issues when deleting a non-empty folder

Ignore that comment. I was confused because I was checking moving, too... :)

**Comment by ocerman** [comment]
> ... typo "realy"

Fixed in opened PR

> If you delete a single folder, the "Delete all" button isn't needed.

It is there beacuse a folder can contains another non-empty folder. Right now the contents of the folder is not examined, so it is displayed even when top folder do not contains another folder.

> If you click "Abort", the "Delete in progress..." alert remains, until you click "Abort" on that one, too. 

Fixed in opened PR
